# Generated by Django 3.1.1 on 2020-11-08 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_was_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
