# Generated by Django 3.1.1 on 2020-11-08 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerplatform', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subledger',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='subledgerUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parententity',
            name='entitynumber',
            field=models.ForeignKey(blank=True, default=None, max_length=8, on_delete=django.db.models.deletion.PROTECT, related_name='entity_no', to='customerplatform.entity'),
        ),
        migrations.AddField(
            model_name='parententity',
            name='parententity_no',
            field=models.ForeignKey(blank=True, default=None, max_length=8, on_delete=django.db.models.deletion.PROTECT, related_name='parent_no', to='customerplatform.entity'),
        ),
        migrations.AddField(
            model_name='annualreports',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='customerplatform.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='annualreports',
            name='entitynumber',
            field=models.ForeignKey(blank=True, default=None, max_length=6, on_delete=django.db.models.deletion.PROTECT, related_name='ntitynumber', to='customerplatform.entity'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountname',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='acctname', to='customerplatform.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='accountno',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='acctno', to='customerplatform.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='acctcat', to='customerplatform.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='entitynumber',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='no_entity', to='customerplatform.entity'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='side',
            field=models.ForeignKey(default=None, max_length=3, on_delete=django.db.models.deletion.PROTECT, related_name='acctside', to='customerplatform.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL),
        ),
    ]
