# Generated by Django 3.1.1 on 2020-11-14 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0002_auto_20201108_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('dealnum', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]*$', 'Only alphanumeric characters are allowed.')])),
                ('dealtype', models.CharField(default=None, max_length=3)),
                ('prodcode', models.CharField(default=None, max_length=25)),
                ('prodtype', models.CharField(default=None, max_length=10)),
                ('currency_code', models.CharField(default=None, max_length=4)),
                ('securityname', models.CharField(blank=True, default=None, max_length=100)),
                ('bond_type', models.CharField(blank=True, default=None, max_length=10)),
                ('isin_code', models.CharField(blank=True, default=None, max_length=25)),
                ('customer_name', models.CharField(blank=True, default=None, max_length=100)),
                ('buyer_country_code', models.CharField(blank=True, default=None, max_length=3)),
                ('buyer_legal_entity_identifier', models.CharField(blank=True, default=None, max_length=50)),
                ('buyer_market_identifier_code', models.CharField(blank=True, default=None, max_length=10)),
                ('delivery_type', models.CharField(blank=True, default=None, max_length=10)),
                ('classification_of_financial_instruments', models.CharField(blank=True, default=None, max_length=10)),
                ('investment_decision_identifier', models.CharField(blank=True, default=None, max_length=12)),
                ('interest_frequency', models.CharField(blank=True, default=None, max_length=8)),
                ('roll_frequency', models.CharField(blank=True, default=None, max_length=12)),
                ('accrual_basis', models.CharField(blank=True, default=None, max_length=100)),
                ('sell_or_purchase', models.CharField(blank=True, default=None, max_length=10)),
                ('portfolio_name', models.CharField(blank=True, default=None, max_length=50)),
                ('business_unit', models.CharField(blank=True, default=None, max_length=10)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accrual_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('accrual_to_date', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('net_position', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('yield_value', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('maturity_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('bcu_principal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('premium_discount_outst', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('premium_discount_to_date', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('premium_discount_daily', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('value_date', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('maturity_date', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('purchase_date', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('lia_date', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('nia_date', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('lrc_date', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('nrc_date', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('accr_daily_from', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('accr_daily_to', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('date_from', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('date_to', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('int_ref', models.CharField(blank=True, default=None, max_length=100)),
                ('hedge_id', models.IntegerField(default=0, null=True)),
                ('hedge_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('option_date', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('expiry_date', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('structure_type', models.CharField(blank=True, default=None, max_length=100)),
                ('hd_deal_number', models.IntegerField(default=0, null=True)),
                ('review_date', models.DateField(blank=True, verbose_name='Entry date dd/mm/yyyy')),
                ('deal_type_group', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
    ]
