# Generated by Django 3.1.1 on 2020-11-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0003_demotable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demotable',
            old_name='accrual_basis',
            new_name='accrual_or_cash_basis',
        ),
    ]
