# Generated by Django 3.1.1 on 2020-11-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0004_auto_20201114_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='demotable',
            name='amortisation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='demotable',
            name='bcu_pamortisation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='demotable',
            name='revaluation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='demotable',
            name='slug',
            field=models.SlugField(default=None, max_length=250),
        ),
    ]
