# Generated by Django 3.1.1 on 2020-11-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0005_auto_20201114_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demotable',
            name='accr_daily_from',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='accr_daily_to',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='dealnum',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='dealtype',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='isin_code',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='lia_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='lrc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='nia_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='nrc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='option_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='value_date',
            field=models.DateField(blank=True, null=True, verbose_name='Entry date dd/mm/yyyy'),
        ),
    ]
