# Generated by Django 3.1.1 on 2020-11-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0006_auto_20201114_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='day',
        ),
    ]
