# Generated by Django 3.1.1 on 2020-11-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0007_remove_demotable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demotable',
            name='bond_type',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='business_unit',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='buyer_market_identifier_code',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='classification_of_financial_instruments',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='dealnum',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='dealtype',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='delivery_type',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='interest_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='interest_frequency',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='investment_decision_identifier',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='new_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='prodcode',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='prodtype',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='roll_frequency',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='sell_or_purchase',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
