# Generated by Django 3.1.1 on 2020-11-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0008_auto_20201114_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demotable',
            name='buyer_country_code',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='currency_code',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
