# Generated by Django 3.1.1 on 2020-11-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0009_auto_20201114_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='interest_due',
        ),
    ]
