# Generated by Django 3.1.1 on 2020-11-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0010_remove_demotable_interest_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='amortisation_amount',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='bcu_pamortisation_amount',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='bcu_principal_amount',
        ),
    ]
