# Generated by Django 3.1.1 on 2020-11-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0011_auto_20201114_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='revaluation_amount',
        ),
    ]
