# Generated by Django 3.1.1 on 2020-11-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0012_remove_demotable_revaluation_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='slug',
        ),
    ]
