# Generated by Django 3.1.1 on 2020-11-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0013_remove_accounts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='premium_discount_daily',
        ),
    ]
