# Generated by Django 3.1.1 on 2020-11-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0014_remove_demotable_premium_discount_daily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='premium_discount_to_date',
        ),
    ]
