# Generated by Django 3.1.1 on 2020-11-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0015_remove_demotable_premium_discount_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='slug',
        ),
        migrations.AddField(
            model_name='accounts',
            name='slug',
            field=models.SlugField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='annualreports',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
    ]
