# Generated by Django 3.1.1 on 2020-11-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0016_auto_20201114_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demotable',
            name='currency_code',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='dealnum',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='dealtype',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='prodcode',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='demotable',
            name='prodtype',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
