# Generated by Django 3.1.1 on 2020-11-14 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0017_auto_20201114_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='accr_daily_from',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='accr_daily_to',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='deal_type_group',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='hd_deal_number',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='hedge_id',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='hedge_percentage',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='int_ref',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='lia_date',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='lrc_date',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='nia_date',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='nrc_date',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='option_date',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='structure_type',
        ),
    ]
