# Generated by Django 3.1.1 on 2020-11-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0018_auto_20201114_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='original_amount',
        ),
    ]
