# Generated by Django 3.1.1 on 2020-11-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0019_remove_demotable_original_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='maturity_date',
        ),
        migrations.RemoveField(
            model_name='demotable',
            name='premium_discount_outst',
        ),
    ]
