# Generated by Django 3.1.1 on 2020-11-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0020_auto_20201114_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demotable',
            name='value_date',
            field=models.DateField(null=True),
        ),
    ]
