# Generated by Django 3.1.1 on 2020-11-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0021_auto_20201115_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='maturity_amount',
        ),
    ]
