# Generated by Django 3.1.1 on 2020-11-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0024_auto_20201115_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demotable',
            name='id',
            field=models.IntegerField(blank=True, default=None, primary_key=True, serialize=False),
        ),
    ]
