# Generated by Django 3.1.1 on 2020-11-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0025_auto_20201115_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demotable',
            name='day',
        ),
    ]
