# Generated by Django 3.1.1 on 2020-11-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0026_remove_demotable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demotable',
            name='delivery_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
