# Generated by Django 3.1.1 on 2020-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0027_auto_20201115_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='demotable',
            name='errors',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='demotable',
            name='issue_description',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
