# Generated by Django 3.1.1 on 2020-11-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerplatform', '0028_auto_20201119_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demotable',
            old_name='errors',
            new_name='count',
        ),
    ]
